### ISSUE TITLE
Support Notebook 7

### ISSUE THREAD

**Issue by jtpio** [deathbeds/jupyterlab-deck#36]
## Elevator Pitch

Thanks for working on `jupyterlab-deck` it looks really promising!

Checking on the JupyterLite demo site with the RetroLab interface and the plugin fails to activate:

![image](https://user-images.githubusercontent.com/591645/202405062-f4d3292a-9702-4794-b785-caa2dda75c54.png)

Probably some dependencies can be made optional. Also `NotebookTools` should now be available in Notebook 7 (https://github.com/jupyter/notebook/pull/6487)

## Motivation

This could serve as an alternative to https://github.com/damianavila/RISE/pull/605 for making RISE-liked presentation in the notebook.

## Design Ideas

N/A

**Comment by jtpio** [comment]
Ah just noticed the question in the README: https://github.com/deathbeds/jupyterlab-deck#does-it-work-with-notebook-7

Indeed multiple documents will be an issue, but maybe there is a way to make it work with just a single document then.

**Comment by bollwyvl** [comment]
Yep went down the "try to make single notebook ux do something it didn't
want to" on nbpresent, not doing that again. Can't just put everything in a
dialog, or keep injecting more _substantive_ Dom everywhere.

If the api is sufficient, wouldn't rule out having a different
plugin/driver that supports the 7 Notebook activity, adapting for quirks,
but other ones just won't make as much sense... Ipydrawio/video-chat showed
me it wasn't very friendly to novel factories.

As for ilabshell: yeah dunno what ended up tipping that, probably some
signal.

**Comment by bollwyvl** [comment]
This is done.
